### ISSUE TITLE
Authenticate with packagist

### ISSUE THREAD

**Issue by Nyholm** [rvanlaak/SettingsBundle#105]
Hey @dmishh 

Could you re-authenticate with Packagist? See here under **Github hook**: https://packagist.org/about

New versions is not showing up :/

**Comment by dmishh** [comment]
Hi @Nyholm ,
I logged in with GitHub on Packagist and pressed Update. Did it help?

**Comment by Nyholm** [comment]
Hey. Thank you. 

It looks good on packages at the moment. Let's see if it updates automatically next time we release a version.

**Comment by Chris53897** [comment]
@Nyholm This issue could probably be closed
